language: node_js
node_js:
  - "stable"
env:
  CI: false
install:
  - npm install
script:
  - npm run build
deploy:
  - provider: pages
    skip-cleanup: true
    target-branch: master
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: ./build
    fqdn: ploypil.in
    on:
      branch: source